### PR TITLE
Autokeras feature added

### PR DESCRIPTION
**Pull request by Sette**
Load image from keras/autokeras and engine example with autokeras/Plant Seedling (Kaggle) added

### CODE REVIEW

**Review by Wei-1 — COMMENTED** [review]
Cool cool!
One concern is that we are still using Python2 ... Will that be an issue?
But even if we are going to change it we can probably handle it in another PR.

**Comment by Sette** [comment]
Autokeras 1.0.3 requires python >= 3.5  and TensorFlow >= 2.2.0. The python-daemon support python3, I fink.

**Comment by Wei-1** [comment]
Hello All, is there anyone who can help to verify this PR?
I am not able to fully track the dependencies of this one.

**Comment by Sette** [comment]
Any suggestions or modifications?

**Comment by Wei-1** [comment]
Sorry @Sette, is there a Markdown file to showcase what this feature can work and how to test it?

**Pull request closed without merging**
