### PR TITLE
Fixing version on test requirements

### PR DESCRIPTION
**Pull request by cardosolucas**
Changing version on test requirements for CI coverage tests fix.

### CODE REVIEW

**Review by Wei-1 — APPROVED** [review]
LGTM, will merge it right after the tests are passed.
Any other concerns?

**Comment by Wei-1** [comment]
`sudo pip install --upgrade pip` failed.. that is weird.
There seem to be some problems with `openssl`
There are these lines in the log:
```
If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.bash_profile
For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

**Comment by cardosolucas** [comment]
Looks like we can manually link it, shall we? Seems like this error doesn't happen all the times.

**Comment by Wei-1** [comment]
Can you re-commit to trigger the CI again?
I think the CI retry feature of Github is still in beta.

**Comment by Wei-1** [comment]
The same error `cannot import name md5`...
I believe there is something wrong here though

**Comment by cardosolucas** [comment]
I hadn't committed yet in the previous test.

**Comment by Wei-1** [comment]
The same error `cannot import name md5`...
You gotta believe there is something wrong here

**Comment by cardosolucas** [comment]
I did some research and I think we have to use brew link openssl --force. Can I try this in this PR?

**Comment by cardosolucas** [comment]
The check is made using the previous version of the file?

**Comment by Wei-1** [comment]
What do you mean?

**Comment by cardosolucas** [comment]
I think Travis is using the .travis.yml version of the official repo to check this PR. Not the changed version. The lines I changed are not appearing in the logs.

**Comment by Wei-1** [comment]
I checked, I think it is using your travis.yml file.
The reason why the test is failing is because you changed line 52 for Linux, but you should also change line 84 for mac as well.

**Comment by oldfly** [comment]
@cardosolucas Python 3.7 installed and python 2.7 rised that error, check which python you are using there

**Comment by cardosolucas** [comment]
It passed with default .travis.yml in this [repo](https://github.com/cardosolucas/incubator-marvin-trytravis). Marvin uses some custom config on travis?

**Comment by oldfly** [comment]
@cardosolucas, there is no customization as far as I know.
I cant find the travis report in your test repo, was the OSX environment build successful?

**Comment by cardosolucas** [comment]
Yes, there is the [link](https://travis-ci.com/cardosolucas/incubator-marvin-trytravis/builds/141609621). The repo has the same modifications of this PR.

**Comment by oldfly** [comment]
@cardosolucas in your link, the OSX log is different then the last failed commit here, from "before_install.9" step.
[here](https://travis-ci.org/apache/incubator-marvin/jobs/620805676?utm_medium=notification&utm_source=github_status)
[there](https://travis-ci.com/cardosolucas/incubator-marvin-trytravis/jobs/268552994)

**Comment by Wei-1** [comment]
Nice! Nice!

**Comment by Wei-1** [comment]
Merged! @cardosolucas

**Pull request merged**
