### PR TITLE
Changing Dockerfile to use Alpine Linux python images

### PR DESCRIPTION
**Pull request by cardosolucas**

### CODE REVIEW

**Review by Wei-1 — COMMENTED** [review]
LGTM, the only problem is that:
Currently, we are having another PR #27, that is fixing the same file.
I think this PR should have a higher priority.
Any other thought?

**Comment by cardosolucas** [comment]
I think that is OK! I submitted this PR thinking about that discussion you guys had in that PR, and it was also a attempt to make a smaller Docker image.

**Comment by Wei-1** [comment]
I will merge the PR this weekend if everyone seems fine with it.

**Comment by rafaelnovello** [comment]
LGTM!

Atenciosamente,
Rafael J. R. Novello

Skype: rafael.novello
Blog: http://rafanovello.blogspot.com.br/


Em seg, 22 de jul de 2019 às 11:26, Wei Chen <notifications@github.com>
escreveu:

**Pull request merged**
