### PR TITLE
Allowing the predictor endpoint to return JSON within result

### PR DESCRIPTION
**Pull request by lucasbmiguel**
Currently, anything that's returned from the engine predictor.py `execute` method, during a POST to /predictor, will be converted to a string. This request introduces the ability for engines to return complex JSON types on HTTP requests for /predictor.

#### How to test:
- Create a new engine and modify the `execute` method of your predictor.py to return a dict with multiple fields.
- Start your engine http server and perform a client POST request to the /predictor endpoint

#### Expected result
You should see a response that contains a JSON inside the "result" field of the top-level response.
Similar to:

```
{
 "result": {
    "myPrediction": "predictedValue",
    "additionalInfo": "toCarry",
    "justANumber": 9
 }
}
```

### CODE REVIEW

**Comment by lucasbmiguel** [comment]
This, fixes MARVIN-77

**Comment by lucasbmiguel** [comment]
This fixes MARVIN-77

**Comment by lucasbmiguel** [comment]
This fixes [MARVIN-77](https://issues.apache.org/jira/projects/MARVIN/issues/MARVIN-77)

**Review by Wei-1 — APPROVED** [review]
Nice nice!
Any other idea? I can merge this PR before Nov.

**Pull request merged**
