### PR TITLE
[MARVIN-19] Init PR to Master

### PR DESCRIPTION
**Pull request by Wei-1**
We did some vital changes to our dev branch already.
Especially for the readme changes, which should be very important for the community to start to participate.
These changes should be made to the master branch so newcomers can easily see.

### CODE REVIEW

**Comment by Wei-1** [comment]
Current failure due to dependency installation failure.
Will implement Travis-ci retry feature to improve the build success rate.
Let's not merge it before retry feature is ready.

**Comment by Wei-1** [comment]
Please check #6 first

**Comment by Wei-1** [comment]
Thanks for merging #6 @oldfly, please help to review this PR @rafaelnovello.

**Comment by rafaelnovello** [comment]
Thanks for all contributions @Wei-1 !

**Pull request merged**
