### PR TITLE
optimization debian package manager tweaks

### PR DESCRIPTION
**Pull request by rajpratik71**
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

### CODE REVIEW

**Review by Wei-1 — COMMENTED** [review]
Please wait until the current dependency issue is fixed, you might need to re-base this commit after that.
https://github.com/apache/incubator-marvin/pull/46

**Review by Wei-1 — COMMENTED** [review]
@Rajpratik71, there are still conflicts in this PR that need to be resolved, can you help to resolve this?

**Comment by rajpratik71** [comment]
> @Rajpratik71, there are still conflicts in this PR that need to be resolved, can you help to resolve this?

rebased to Upstream and resolved the conflict

**Review by Wei-1 — COMMENTED** [review]
Cool, I will merge this PR is no other opinion from others

**Pull request merged**
