### PR TITLE
[MARVIN-57] Bump sbt from 0.13 to 1.x

### PR DESCRIPTION
**Pull request by jiminhsieh**
Bump sbt from 0.13.9 to 1.2.8 and update replated sbt-plugins

### CODE REVIEW

**Comment by Wei-1** [comment]
We will merge #26 today, please rebase on it after we merge that.

**Comment by jiminhsieh** [comment]
Got it. :)

**Review by Wei-1 — COMMENTED** [review]
PR #26 merged, please help to include the commit to pass the CI

**Review by Wei-1 — APPROVED** [review]
LGTM, I will merge this PR this weekend if no other comment.

**Pull request merged**
