### PR TITLE
Tutorial book update

### PR DESCRIPTION
**Pull request by oldfly**
All installation guide links were out of date. 
referring Issue MARVIN-14

### CODE REVIEW

**Comment by Wei-1** [comment]
One question @oldfly and @rafaelnovello , is there a plan that we move all these documents under Apache?

**Comment by oldfly** [comment]
> One question @oldfly and @rafaelnovello, is there a plan that we move all these documents under Apache? Not in this PR for sure, just asking.

Hi @Wei-1 , we are still discussing about this, but I think it's better to bring these docs to apache infrastructure. Please feel free to suggest anything, We are new to the community and we have many things to learn. Thanks!!!

**Comment by Wei-1** [comment]
I recognize that we will have another repository in ASF group for Marvin-AI website from the dev mails.
So these reources will be put to that website repo, and the links will be pointing to those new resources when it is ready right?

**Comment by oldfly** [comment]
Yes, exactly! We need your help for sure.
I'll check the situation of the website repository and warn you when everything is ready.

**Comment by oldfly** [comment]
Hello @Wei-1 , i have created the repo for website: "https://gitbox.apache.org/repos/asf?p=incubator-marvin-website.git" and pushed the apache website template into it.
What should we do now? Restructure the original marvin website code by adapting the template?

**Comment by Wei-1** [comment]
> What should we do now? Restructure the original Marvin website code by adapting the template?

Cool! Thx @oldfly! I will check and submit PR there: https://github.com/apache/incubator-marvin-website

**Pull request merged**
