### PR TITLE
CodeCov related changes:

### PR DESCRIPTION
**Pull request by tallandroid**
- Started reporting the coverage for scala during travis build

### CODE REVIEW

**Comment by tallandroid** [comment]
https://codecov.io/gh/apache/incubator-marvin/pull/36/list/ 

CodeCov post the commit.

**Review by Wei-1 — COMMENTED** [review]
This PR is great! Finally have both languages covered.

**Comment by tallandroid** [comment]
@Wei-1 any concerns with the PR? Can we close this?

**Comment by Wei-1** [comment]
LGTM, I will close this today.

**Pull request merged**
