### PR TITLE
[MARVIN-47] Scala Package Name Update (revert-rename-history)

### PR DESCRIPTION
**Pull request by Wei-1**
Update package from org.marvin to org.apache.marvin
Also, try to revert the history of directory rename

### CODE REVIEW

**Review by Wei-1 — COMMENTED** [review]
Note that we might need to force push to gitbox to revert the history of directory rename.
Can you help to review this one @takabayashi, @oldfly, @lucasbm88 
I will push to Gitbox after your validation.

**Review by lucasbmiguel — COMMENTED** [review]
looks good in general. I am not sure if it's a good idea to push the engine-executor and python-toolbox bin files in the build directory tho. Should we remove them and add some sort of file exists check in the build scripts? If they don't exist we can either build them or fail with a message asking the user to explicitly build them.

**Comment by Wei-1** [comment]
It is a good point.
It will be better if we can download the jar file from some hosts in the Dockerfile.
However, refer to this issue: https://issues.apache.org/jira/projects/MARVIN/issues/MARVIN-56
We currently are not able to download the jar file.
Do you think we should still remove it?

**Comment by Wei-1** [comment]
Let's wait until @oldfly finish [MARVIN-45](https://issues.apache.org/jira/browse/MARVIN-45)
and we modify the build process

**Comment by Wei-1** [comment]
On second thought, let's merge this first.
We can handle the bin file history after we are good with the sonatype artifact.
If everyone is good with that, I will merge it tomorrow.

**Comment by Wei-1** [comment]
Note that we are not able to revert the file name changing history since we didn't force push the pull request.

**Pull request merged**
