### PR TITLE
Update the engine template Dockerfile to install opensdk

### PR DESCRIPTION
**Pull request by rafaelnovello**
We don't have unit tests for Dockerfile

### CODE REVIEW

**Review by Wei-1 — COMMENTED** [review]
LGTM
I think we can add the Docker build test in Tracis-CI in another PR.
just fyi: [a ref I found](https://bencane.com/2016/01/11/using-travis-ci-to-test-docker-builds/)

**Comment by rafaelnovello** [comment]
> LGTM
> I think we can add the Docker build test in Tracis-CI in another PR.
> just fyi: [a ref I found](https://bencane.com/2016/01/11/using-travis-ci-to-test-docker-builds/)

Wei, I can't do it right now (sorry) but I believe it's a good idea.
I think we can open a issue for that!

**Review by takabayashi — CHANGES_REQUESTED** [review]
Testing I got this error:

`no such option: --process-dependency-links`

Basically, you need to remove this flag from the template Dockerfile.

**Comment by rafaelnovello** [comment]
@takabayashi could you test again please?

**Comment by Wei-1** [comment]
This is becoming a blocking issue for other PRs, I will merge it today if no other opinions.

**Review by takabayashi — APPROVED** [review]

**Comment by takabayashi** [comment]
Ok everything looks fine. Lets, merge it.

**Pull request merged**
